improve translation extraction tool to recognize all relevant patterns
Blair2004/NexoPOS pull request #1321
Opened 2023-02-18 17:00 UTC by swurzinger

- save translations json pretty-printed, so no additional formatting is required (could be minified for the production build)
 - fix translation extraction logic to detect translation strings more reliably
 - do not search for translation strings in comment blocks /* */
 - ignore resources/views/generate folder when searching for translation strings

2023-02-18 23:09 UTC, swurzinger commented
rebased & retargeted onto 4.8 branch

2023-02-19 09:27 UTC, Blair2004 requested changes

2023-02-19 09:27 UTC, Blair2004 commented on app/Console/Commands/ExtractTranslation.php
> +        Storage::disk( 'ns' )->put( 'lang/' . $lang . '.json', json_encode( $finalArray, JSON_PRETTY_PRINT ) );
Hey, this will increase the size of the translation files. This will rather increase loading time. Note that on IDE like VSCODE, it's possible to format raw json content. I believe this change is not necessary.

2023-02-19 09:27 UTC, Blair2004 commented on app/Console/Commands/ExtractTranslation.php
> +            foreach ( $excludedDirectories as $excludedDir ) {
That's a good idea to exclude the "generate" folder.

2023-02-19 12:55 UTC, swurzinger commented on app/Console/Commands/ExtractTranslation.php
> +        Storage::disk( 'ns' )->put( 'lang/' . $lang . '.json', json_encode( $finalArray, JSON_PRETTY_PRINT ) );
We should differentiate between source code and build artifacts here IMO. The lang files in the repository shouldn't be minified, just the bundled ones in the `public/lang` folder.
It makes git diffs pretty much useless otherwise.

I'll try to modify the webpack config to minify the lang files during bundling.

2023-02-19 15:06 UTC, swurzinger commented on app/Console/Commands/ExtractTranslation.php
> +            foreach ( $excludedDirectories as $excludedDir ) {
Ideally that wouldn't be needed, though. But I can't think of an easy way to detect that these occurences shouldn't be processed. A small improvement could be to not hardcode the directories, but having a marker-file (e.g. ".no-i18n") in the respective folder(s) instead. Or having some way to explicitly ignore translations in a specific file or even a specific block of a file only.

2023-02-19 15:26 UTC, swurzinger commented on app/Console/Commands/ExtractTranslation.php
> +        Storage::disk( 'ns' )->put( 'lang/' . $lang . '.json', json_encode( $finalArray, JSON_PRETTY_PRINT ) );
Added some changes to replace the lang-folder symlinking by minify during bundle creation. I'm not a 100% happy with the current implementation as it doesn't integrate with Laravel Mix too well, but I think it's better than symlinking. Kept the symlink behaviour for modules untouched.

2023-02-19 15:55 UTC, Blair2004 commented on app/Console/Commands/ExtractTranslation.php
> +        Storage::disk( 'ns' )->put( 'lang/' . $lang . '.json', json_encode( $finalArray, JSON_PRETTY_PRINT ) );
Hey, thank you for this. There is few points I would like to highlight.

1 - We would like users avoid having to bundle the app using node.js preferably. That will reduce steps to have the project working. If we implement this, we'll have to bundle the app and attach the binary to the release.

2 - Laravel Mix is dropped on V5, we're using Vite instead.

If the suggested solution doesn't add an extra step on installing the app, then it should be fine. I understand we should have uncompressed language file, that will also easy reading.

2023-02-19 15:58 UTC, Blair2004 commented
It seems like this implementation will force the user to build the app before deploying. If we have to build the app ourselves and attach it to releases, we'll have 2 references for the same file (compressed and uncompressed).

I'm not sure to understand what was the concerns with the symlink strategy and the compressed localization files ?

2023-02-19 16:34 UTC, swurzinger commented on app/Console/Commands/ExtractTranslation.php
> +        Storage::disk( 'ns' )->put( 'lang/' . $lang . '.json', json_encode( $finalArray, JSON_PRETTY_PRINT ) );
1. It works the same as for the bundling of JS/CSS/.. files in general. If the user shouldn't have to build the application then the build artifacts need to be either committed in the repository (which seems to be already done, e.g. in the `public/js` folder) or the release package is different from the repository contents (repo contains sources only, release contains bundled files and assets only). I'd prefer the latter to keep the repo clean (not having any build artifacts there), but there are valid reasons for both.
So when using the first approach there should be (formatted) source code in the `lang`-folder and (minified) assets in the `public/lang`-folder.

2. Nice to hear that recent technologies are adopted. I had a look at the v5 branch and the implementation still seems incomplete (e.g. Mix is still used in package.json run configurations/dependencies and mix-specific config files like `webpack.mix.js` are still there). According to the [documentation](https://vitejs.dev/guide/assets.html#the-public-directory) static assets should be placed in the public directory directly. Copying static assets, as known from webpack or Mix doesn't seem to be supported or recommended to do. Thus ideally there would be some tool to do the minification and write the lang files to the public folder. Not sure what's the recommended approach to do that, could be done by a artisan command/migration, npm script or bundler plugin.

2023-02-19 16:53 UTC, swurzinger commented
> It seems like this implementation will force the user to build the app before deploying. If we have to build the app ourselves and attach it to releases, we'll have 2 references for the same file (compressed and uncompressed).
> 
> I'm not sure to understand what was the concerns with the symlink strategy and the compressed localization files ?

As explained in more detail above the build artifacts (i.e. compressed lang jsons) need to be in the repo as well if the user shouldn't need to build them.

What I don't like is mixing sources and binaries (or in this case compressed and uncompressed assets). If they are binaries they should be compressed and located in the `/public` folder (or a subfolder), not in `/lang`. If they are sources the location is fine but they shouldn't be compressed.

2023-02-19 17:33 UTC, Blair2004 commented
I get the point. I think the final solution should be to create an artisan command that is added to composer "scripts" on "post-install-cmd". That command will be in charge of copying the translations from source and put them on the public/lang directory by compressing those files ideally during the process.

2023-02-19 18:05 UTC, Blair2004 commented
After further thoughts, this strategy should also be implemented for module. But, module aren't installed using composer, so coying files instead of symlinking in that particular case doesn't seems a suitable solution.

2023-04-10 08:45 UTC, Blair2004 commented
Closed for inactivity.

2023-04-10 08:45 UTC, closed without merging

2025-02-02 18:59 UTC, swurzinger commented
The RegEx in https://regex101.com/r/tegn0g/1 gives a few examples of translations currently used in the application sources. The current implementation on master is still broken for a few cases (see sample on Regex101, try with expression from master).
See https://github.com/swurzinger/NexoPOS/blob/stw/5-generic/app/Console/Commands/TranslateCommand.php#L188 for a working implementation.