fix typos and other minor translation issues
Blair2004/NexoPOS pull request #1322
Opened 2023-02-18 17:12 UTC by swurzinger

- fix typos in code, comments and translations
   - no changes in DB structure
- remove duplicate translation strings
- fix some DE/IT/FR/ES translations

2023-02-18 23:10 UTC, swurzinger commented
will rebase onto 4.8 after #1321 is merged

2023-02-19 09:18 UTC, Blair2004 requested changes
Hi,
I couldn't imagine there was that much typos... Your contribution is amazing.
Thank you so much.

There is a change need regarding the an attribute name which is currently persistent on users installation. We need to create a migration that update the column name on current installations.

2023-02-19 09:18 UTC, Blair2004 commented on tests/Traits/WithExpenseTest.php
> +                    'occurrence' => 'month_starts',
A database migration is needed to update the existing installations (current users installation) that has this attribute on the database. Unless the migration is added to the PR, this should be skipped for now.

2023-02-19 15:36 UTC, swurzinger commented on tests/Traits/WithExpenseTest.php
> +                    'occurrence' => 'month_starts',
thanks, I reverted some other usages of `occurence` related to DB entities, but must have missed these ones. I guess fixing the DB column name as well as the name in data structures is not worth the effort as it's a breaking change for existing modules.

2023-02-19 16:00 UTC, Blair2004 commented on tests/Traits/WithExpenseTest.php
> +                    'occurrence' => 'month_starts',
We'll ship this for v5 and suggest modules to update their implementation as well.

2023-02-19 16:02 UTC, Blair2004 approved these changes

2023-02-19 16:03 UTC, merged