Miscellaneous small fixes and improvements for v5.0
Blair2004/NexoPOS pull request #1469
Opened 2023-05-03 21:43 UTC by swurzinger

A collection of various smaller fixes and improvements for v5. Some of them have already been implemented recently on v5 and thus aren't included in the changes anymore:

 - show users, who are not in any group
 - avoid NPE in DateCast
 - product edit: don't hide images tab
 - more flexible product categories 
 - fix single delivery type loop, immediately hide selection dialog again
 - add to cart performance improvements
 - hide delivery types button when there's just a single one
 - fix payment dialog reactiveness
 - fix CORS/CSRF configuration
 - fix setup frontend navigation
 - fix price display, show full customer name
 - fix tabs selection via active property as used in pos-customers
 - POS: hide taxes button, when taxes are disabled
 - POS: fix product removal
 - POS: fix quantity change, minor typos
 - minor UI: avoid jumping scrollbar when spinner is active
 - fix layaway popup, fix pending order currency formatting
 - fix customer search, fix customer statement report
 - POS: fix customer selection popup
 - avoid endless loop when using invalid date
 - POS: fix cash register imports, add ts interface
 - replace deprecated vue lifecycle hooks
 - fix order products popup price
 - POS: fix cart-products switching, fix account full payment
 - add full customer name as calculated attribute, simplify name display
 - fix text readability (light theme)
 - fix layaway and manual payment
 - deduplicate payment status mapping

2023-05-03 21:48 UTC, swurzinger commented
Inteded to be sqashed before being merged. Didn't do it yet because maybe you want only a subset of the changes and some of them need to be reverted.

2023-05-04 00:44 UTC, Blair2004 requested changes
There are personal changes that don't apply to the core project.

2023-05-04 00:46 UTC, Blair2004 requested changes
This doesn't apply to the core project

2023-05-04 00:47 UTC, Blair2004 approved these changes

2023-05-04 00:47 UTC, Blair2004 requested changes
Doesn't apply to the core project

2023-05-04 00:48 UTC, Blair2004 requested changes
What does this solves ?

2023-05-04 00:49 UTC, Blair2004 requested changes
That's not a desired behavior. On grouped, products, we rather want to hide certain tabs.

2023-05-04 00:51 UTC, Blair2004 reviewed
Not sure to understand this approach. Can you describe ?

2023-05-04 00:54 UTC, Blair2004 requested changes

2023-05-04 00:54 UTC, Blair2004 commented on resources/ts/libraries/popup.ts
> +        if (immediately) {
This approach doesn't seems convenient.

2023-05-04 00:54 UTC, Blair2004 commented on resources/ts/popups/ns-pos-order-type-popup.vue
> +        this.typeSubscription   =   POS.types.pipe(take(1)).subscribe( types => {
why would we take 1 types instead of all?

2023-05-04 00:54 UTC, Blair2004 requested changes
Not applicable to the core project

2023-05-04 00:55 UTC, Blair2004 requested changes
This is not a great fit as it also applies to production.

2023-05-04 00:57 UTC, Blair2004 reviewed
Building assets is part of the project as this avoids the need to install node, dependencies, and assets. A better solution is needed for taking this in consideration.

2023-05-04 01:00 UTC, Blair2004 requested changes
we rather like the object implementation for cart button (instead of array).
Showing delivery button if 2 types are available doesn't consider the case if only Delivery is available as the only option.

2023-05-04 07:16 UTC, swurzinger commented on resources/ts/popups/ns-pos-order-type-popup.vue
> +        this.typeSubscription   =   POS.types.pipe(take(1)).subscribe( types => {
The subscription here calls `select(type)` when there's only a single type and the select method then changes the types again with `types.next(...)`, leading to an endless loop. As the type subscription is used for initialization only I thought it's fine to only take the first and ignore anything else. It did work in my tests, but probably there's a better way to solve this. I'd be greatful about any ideas. :-)

2023-05-04 07:21 UTC, swurzinger commented on resources/ts/libraries/popup.ts
> +        if (immediately) {
The problem I try to solve here is that the popup causes a delay of 250ms even if it isn't used (is immediately closed after being called, usually because there's nothing to choose from). The implementation changed slightly in a later commit due to your popup injection changes. Could you suggest a better approach I could implement?

2023-05-04 07:39 UTC, swurzinger commented
> Building assets is part of the project as this avoids the need to install node, dependencies, and assets. A better solution is needed for taking this in consideration.

I just removed all the build artifacts from the repo on my branch, reverted all those changes for this PR. So this PR shouldn't contain any changes to the assets.

> we rather like the object implementation for cart button (instead of array). Showing delivery button if 2 types are available doesn't consider the case if only Delivery is available as the only option.

You mean there is a case when there's a single delivery type but you still want to show the delivery type selection dialog? Do you maybe have an example? Because I don't understand yet why one would need that.

2024-02-13 02:23 UTC, Blair2004 commented
I believe those changes are no longer applicable to the current state of the app. A new PR might be necessary.
Thank you for the contribution.

2024-02-13 02:23 UTC, closed without merging

2024-02-13 19:55 UTC, swurzinger commented
Most of the changes are still applicable to the latest NexoPos version, but this PR would need to be rebased. However, I chose to maintain a fork instead: https://github.com/swurzinger/NexoPOS/tree/stw/5-generic
Feel free to grab any fixes/improvements from there 😀